# Generated by Django 2.2 on 2021-08-11 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='关键字')),
                ('picture_url', models.CharField(max_length=200, verbose_name='图片url')),
                ('link_url', models.CharField(blank=True, max_length=200, verbose_name='点击url')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('source', models.CharField(max_length=32, verbose_name='来源')),
                ('check_num', models.IntegerField(verbose_name='点击量')),
                ('read_times', models.IntegerField(verbose_name='阅读量')),
                ('article_num', models.IntegerField(verbose_name='文章数量')),
                ('order_num', models.IntegerField(verbose_name='订阅量')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('is_brand', models.IntegerField(verbose_name='品牌')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名字')),
            ],
            options={
                'verbose_name': '图片新闻表',
                'verbose_name_plural': '图片新闻表',
                'db_table': 'tb_news_writer',
            },
        ),
    ]
