# Generated by Django 2.2 on 2021-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=200, verbose_name='图片url')),
                ('link_url', models.CharField(max_length=200, verbose_name='点击url')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('mod', models.CharField(max_length=32, verbose_name='模块')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '广告轮播表',
                'verbose_name_plural': '广告轮播表',
                'db_table': 'tb_advertising',
            },
        ),
    ]
