# Generated by Django 2.2 on 2021-08-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSearchKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32, verbose_name='关键词')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('serch_numbers', models.IntegerField(default=0, verbose_name='次数')),
            ],
            options={
                'verbose_name': '新闻搜索日志表',
                'verbose_name_plural': '新闻搜索日志表',
                'db_table': 'tb_news_serch',
                'ordering': ['-serch_numbers'],
            },
        ),
    ]
